trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Pipeline Container Update
  displayName: Updating Container
  jobs:
  - job: Update
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        apt update
  - job: Update
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        apt upgrade -y