trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: PipelineContainerUpdate
  displayName: Updating Container
  jobs:
  - job: UpdateContainer
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        apt update
  - job: UpgradingContainer
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        apt upgrade -y

- stage: InsatallSonarScanner
  displayName: Install Sonar Scanner
  jobs:
  - job: UpdateContainer
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        apt update