trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_USERNAME: $(DockerUsername)
  DOCKER_PASSWORD: $(DockerPassword)
  IMAGE_NAME: "sanchit"
  IMAGE_TAG: "latest"
  SONAR_HOST_URL: "http://172.172.107.149:9000/"
  SONAR_PROJECT_KEY: "Sansitor_node-hello_AZX1oNOx4D1I2PVSzYCV"
  SONAR_LOGIN_TOKEN: sqa_355d2cc7c5a08b4edf74ff2f377f613a9dc0ea45
  VM_IP: "172.172.107.149"
  VM_USERNAME: "ranjeet"
  VM_PASSWORD: "ranjeet@123qwe"

stages:
- stage: QualityGateStatus
  displayName: Quality Gate Status
  jobs:
  - job: CheckQualityGate
    displayName: Checking Quality Gate
    steps:
    - script: |
        echo "Checking Quality Gate status..."
        SONAR_API_URL="$(SONAR_HOST_URL)/api/qualitygates/project_status?projectKey=$(SONAR_PROJECT_KEY)"
        STATUS=$(curl -s -u "$(SONAR_LOGIN_TOKEN):" "$SONAR_API_URL" | jq -r '.projectStatus.status')

        if [ "$STATUS" == "OK" ]; then
          echo "Quality Gate Passed ✅"
          exit 0
        else
          echo "Quality Gate Failed ❌"
          exit 1
        fi
      displayName: Checking Quality Gate