trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_USERNAME: $(DockerUsername)
  DOCKER_PASSWORD: $(DockerPassword)
  IMAGE_NAME: "sanchit"
  IMAGE_TAG: "latest"
  SONAR_HOST_URL: "https://sonarcloud.io"
  SONAR_PROJECT_KEY: "Sansitor_node-hello"
  SONAR_ORGANIZATION: "sansitor"
  SONAR_TOKEN: "b82435da279c822822d17553d2a6432a9b655b6c"
  VM_IP: "20.57.119.143"
  VM_USERNAME: "sanchit"
  VM_PASSWORD: "sanchit@123qwe"

stages:
- stage: PipelineContainerUpdate
  displayName: Updating Container
  jobs:
  - job: UpdateContainer
    displayName: Updating
    steps:
    - script: |
        echo "Updating Container"
        sudo apt update
      displayName: Updating Container
  - job: UpgradingContainer
    displayName: Upgrading
    dependsOn: UpdateContainer
    steps:
    - script: |
        echo "Upgrading Container"
        sudo apt update
      displayName: Upgrading Container
      
- stage: SonarScan
  displayName: 'SonarCloud Scan'
  dependsOn: PipelineContainerUpdate
  jobs:
    - job: RunSonarCloud
      displayName: 'Run SonarCloud Scan'
      steps:
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloudConnection'  # Define this in service connections
            organization: '$(SONAR_ORGANIZATION)'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: '$(SONAR_PROJECT_KEY)'
            cliSources: '.'

        - script: |
            echo "Running SonarCloud scanner"
            sonar-scanner
          displayName: 'Run Sonar Scanner'

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'



- stage: BuildAndPushImage
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildDockerImage
      displayName: 'Build , Scan & Push Docker Image'
      steps:
        - script: |
            echo "Logging in to Docker Hub..."
            echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
          displayName: 'Logging into Container Registries'

        - script: |  
            echo "Building image: $(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)"
            docker build . -t "$(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)"
          displayName: 'Building Docker Image'

        - script: | 
           curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
            sh install-scout.sh
            docker scout cves \
              --format only-packages \
              --only-vuln-packages \
              --output $(Build.ArtifactStagingDirectory)/docker_scout_report.json \
              "$(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)"
          displayName: 'Installing Docker Scout & Scanning Image'
            
        - script: |
            docker push "$(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)"
          displayName: 'Pushing the image to Docker Hub'

        - publish: $(Build.ArtifactStagingDirectory)/docker_scout_report.json
          artifact: docker_scout_report    
          displayName: 'Publish Docker Scout Report'
        
        - script: |
            docker save -o $(Build.ArtifactStagingDirectory)/sanchit.tar "$(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)"
          displayName: 'Saving Docker Image as sanchit.tar'

        - publish: $(Build.ArtifactStagingDirectory)/sanchit.tar
          artifact: docker_image_tar
          displayName: 'Publish Docker Image Tar File'
        
- stage: CopyToVM
  displayName: 'Copy to VM'
  jobs:
    - job: CopyToVM
      displayName: 'Copying Image Tar file to VM.'
      steps:
      - download: current
        artifact: docker_image_tar
        displayName: 'Download Docker Image Tar'
      - script: |
         docker load -i $(Pipeline.Workspace)/docker_image_tar/sanchit.tar
         sudo apt -y install sshpass
         mkdir -p ~/.ssh
         ssh-keyscan $(VM_IP) >> ~/.ssh/known_hosts
         sshpass -p $(VM_PASSWORD) scp $(Pipeline.Workspace)/docker_image_tar/sanchit.tar $(VM_USERNAME)@$(VM_IP):/home/ranjeet/
         sshpass -p $(VM_PASSWORD) scp $(Build.SourcesDirectory)/container_start.sh $(VM_USERNAME)@$(VM_IP):/home/ranjeet/
         sshpass -p $(VM_PASSWORD) ssh $(VM_USERNAME)@$(VM_IP) 'bash /home/ranjeet/container_start.sh'
        displayName: 'Copy Docker Image Tar to Azure VM using Username & Password'